name: Self Test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build
        run: |
          bun run build
          ls -la dist
          
      - name: Run PR Analysis on this repo
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}
          pr-number: ${{ github.event.pull_request.number || 1 }}
          llm-api-key: ${{ secrets.LLM_API_KEY }}
          llm-provider: 'openai'
          comment-rules: |
            {
              "customInstructions": "Focus on TypeScript best practices and code quality"
            }
          log-level: "debug"