name: Self Test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Check file contents
        run: |
          echo "--- bunfig.toml ---"
          cat bunfig.toml || echo "File not found"
          echo "--- action.yml ---"
          cat action.yml || echo "File not found"
          echo "--- .musashi (if exists) ---"
          cat .musashi || echo "File not found"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
          bun run build
          ls -la dist

      - name: Run PR Analysis on this repo
        uses: ./
        with:
          github-token: ${{ secrets.MUSASHI }}
          # repo-name will use default (github.repository)
          pr-number: ${{ github.event.pull_request.number || 1 }}
          llm-api-key: ${{ secrets.LLM_API_KEY }}
          llm-provider: "openai"
          exclude-paths: "src/types.ts,**/*.html,dist/**,**/*.md"
          # Rules will be read from .musashi file if it exists
          log-level: "debug"
